### ISSUE TITLE
Website: Clean up CSS

### ISSUE THREAD

**Issue by srmagura** [TypeStrong/typedoc#1776]
**Problem:** Overly large space between certain headings:

![image](https://user-images.githubusercontent.com/801549/139564422-73752a8d-51db-4f47-b734-af0337fb277b.png)

**Solution:** Use only `margin-bottom`. Remove `margin-top` from headings and paragraphs.

**Problem:** Can't add margin [in certain cases where it would be beneficial](https://github.com/TypeStrong/typedoc-site/pull/48/files#diff-f131fc9dca7d0116bd2258c95e127905bb0db3b922c83db9c7648b32770fc532R729) because of CSS like this:

```css
.col-11 > *:first-child,
.col-sm-11 > *:first-child {
    margin-top: 0;
}
.col-11 > *:last-child,
.col-sm-11 > *:last-child {
    margin-bottom: 0;
}
```

**Solution:** Column classes should not mess with margin of the first or last child.
