### ISSUE TITLE
Is it possible to render the navigation pane on the left?

### ISSUE THREAD

**Issue by ilg-ul** [TypeStrong/typedoc#2189]
Is there any way to render the site with the two main panes reversed, i.e. with the navigation pane on the left?

I know that this is a subjective matter, but most sites (including <https://typedoc.org/guides/overview/>!) has the navigation tree in the left pane.

Thank you!

**Comment by Gerrit0** [comment]
You could do this pretty easily with the [customCss](https://typedoc.org/guides/options/#customcss) option

```css
.container-main {
  flex-direction: row-reverse;
}

@media (min-width: 1024px) {
  .col-content {
    padding-left: 2rem;
    padding-right: 0;
  }
  .col-menu {
    border-left: 0;
    border-right: 1px solid var(--color-accent);
  }
}
```
