### ISSUE TITLE
Ability to generate source links independent of the git repository (CI, gitlab)

### ISSUE THREAD

**Issue by blutorange** [TypeStrong/typedoc#2326]
## Search Terms

gitlab github ci pipeline source links missing repository

## Problem

Before I state my problem, let me first of all say that the new documentation pages TypeDoc generates look awesome! I did not work on a frontend project for a couple of years, it's a real improvement.

I was trying to generate TypeDocs via gitlab pipelines. This works as expected, but I noticed that the source links are missing. They are generated correctly when I run TypeDoc locally.  After some experimentation, I noticed that when gitlab is running pipelines, there is no `.git` repository, or at least not a fully initialized one. I was thinking that it should be possible to generate source links `--sourceLinkTemplate` and `--gitRevision` are provided as options, but that did not work.

For generating source links, TypeDoc seems to require at least (a) that git is installed, (b) that there exists a git repo in the workspace folder and (c) that the files are in a commit. For (a), the `git` command might not even exist in a CI environment.

## Suggested Solution

Provided that `--sourceLinkTemplate` and `--gitRevision` are given, should it not be possible to generate source links from the path of the files alone? Perhaps a `--gitRoot` option might make sense, but when running in a CI environment, that will be the root folder.

## Workaround

For gitlab pipelines, my current workaround is to initialize a dummy git repository and delete it afterwards

```yaml
# Create gitlab pages with documentation
pages:
  stage: docs
  image: timbru31/node-alpine-git:16
  script:
    # TypeDoc does not generate source links unless there is a git repo
    - echo "Creating dummy git repo and commit for TypeDoc..."
    - rm -r .git
    - git init
    - git config user.email john.doe@example.com
    - git config user.name "John Doe"
    - git add -A
    - git commit -m dummy
    # Actual doc generation
    - echo "Generating docs for release..."
    - yarn typedoc
  after_script:
    - rm -r .git
  artifacts:
    paths:
      - public
```
