### ISSUE TITLE
Menu alignment change in v0.24.x

### ISSUE THREAD

**Issue by vitaly-t** [TypeStrong/typedoc#2345]
After upgrading from v0.23.x to v0.24.x, the menu jumped from right to left.

How can I get it to display on the right side again?

**Comment by Gerrit0** [comment]
```css
@media (min-width: 1200px) {
  .container-main {
    grid-template-areas: "toc content sidebar";
  }
}
```

Stick that in a file, and point typedoc to it with `--customCss`

**Comment by vitaly-t** [comment]
It works only in part...

Here's how it looked in version 0.23.x:

<img width="1339" alt="image" src="https://github.com/TypeStrong/typedoc/assets/5108906/be2a1d7b-97e0-4d56-806e-e90d58ebe41b">

And here how it looks in version 0.24.x, after adding that CSS snippet:

<img width="1422" alt="image" src="https://github.com/TypeStrong/typedoc/assets/5108906/0bc59ef2-c256-468f-af86-fb7f0bdeb02e">

i.e. we now have `Settings` occupy extra space, unfortunately...

P.S. I really preferred the old look.... ;)

**Comment by vitaly-t** [comment]
@Gerrit0 Do know if it is possible, via some other CSS, to make it look like the previous version (as per above)? I just want the `Settings` section back in the right top as before. Thanks!

**Comment by Gerrit0** [comment]
I don't have time to support everyone's custom setup. This is why customCss exists. Took me like 30 minutes to remember how that CSS works and make it work properly... and I don't have time for TypeDoc during the week, or on every weekend.

```css
@media (min-width: 770px) {
  .container-main {
    grid-template-columns: minmax(0, 2fr) minmax(0, 1fr);
    grid-template-areas: "content sidebar";
  }
  
  .col-sidebar {
     display: block;
  }
  
  .page-menu, .site-menu {
    position: static;
    margin-top: 0;
    max-height: inherit;
  }
  
  .col-sidebar {
        max-height: calc(100vh - 2rem - 42px);
        overflow: auto;
        position: sticky;
        top: 42px;
    }
}
```
