### ISSUE TITLE
Missing Table Styles in CSS

### ISSUE THREAD

**Issue by stuft2** [TypeStrong/typedoc#2366]
## Search terms

readme markdown table css style

## Expected Behavior

Render tables in a similar style to the rest of the typedoc theme. I added these styles to a custom css file that I include in my typedoc output via the --customCss flag:

```css
table {
    border-collapse: collapse;
    width: 100%;
    border: none;
}
th {
    background-color: rgba(93, 93, 106, 0.53);
}
td {
    background-color: rgba(30, 32, 36, 0.47);
}
th, td {
    border: 1px solid rgba(0, 0, 0, 0.51);
    padding: 8px;
    text-align: left;
}
```

## Actual Behavior

There are no table styles at all.

## Steps to reproduce the bug

1. Add a README.md file at the root
2. Add a table to the README.md file
3. Generate documentation with default typedoc theme
4. Open the index.html file to view the missing table styles

[Reproduction PR](https://github.com/TypeStrong/typedoc-repros/pull/29)

## Environment

-   Typedoc version: 0.24.8
-   TypeScript version: 5.1.6
-   Node.js version: 18.14.0
-   OS: MacOS Ventura (13.3.1)
