### ISSUE TITLE
types used in Returns section of functions are shown in white instead of green / red

### ISSUE THREAD

**Issue by sapphi-red** [TypeStrong/typedoc#2546]
## Search terms

default theme, returns, function, link, css

## Expected Behavior

Types with a link in "Returns" section of functions are shown in green / red (depending on whether it is a type or interface).

![image](https://github.com/TypeStrong/typedoc/assets/49056869/2e8897df-09ef-4995-b965-829be16be7ed)

(I tweaked the CSS a bit to make this image)

## Actual Behavior

Types with a link in "Returns" section of functions are shown in white.

https://typedoc.org/api/functions/JSX.createElement.html
![image](https://github.com/TypeStrong/typedoc/assets/49056869/24631774-8deb-4173-a8cf-9fba68a15dcf)

It seems
```css
h1 > a:not(.link), h2 > a:not(.link), h3 > a:not(.link), h4 > a:not(.link), h5 > a:not(.link), h6 > a:not(.link) {
    text-decoration: none;
    color: var(--color-text);
}
```
is overriding the color.

## Steps to reproduce the bug

See the actual behavior section.

## Environment

-   Typedoc version: 0.25.13
-   TypeScript version: 5.3.3
-   Node.js version: 20.11.1
-   OS: Windows
